name: LOL APPROVAL workflow bro
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
      uses: pullreminders/label-when-approved-action@master
      name: label when approved bro
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #not sure about this one
        ADD_LABEL: "my own action works!!"